title:
  en: Di Yang
  zh: 杨迪
  ja: アンディ
subtitle:
  en: "Hello, I'm Di Yang."
  zh: "你好，我是杨迪。"
  ja: "こんにちは、私はアンディです。"
introduction:
  en: >
    <h1>Hello, I'm <a href="/about/">Di Yang</a>.</h1>
    <h2> How are you ? </h2>
  zh: >
    <h1>你好，我是<a href="/关于/">杨迪</a>。</h1>
    <h2>我就是填充文字，不要理我哦。</h2>
  ja: >
    <h1>こんにちは、私は<a href="/紹介/">アンディ</a>です。</h1>
    <h2>自己紹介？わからんわ。　何をすればいいかな</h2>
keywords: "Di,Di Yang,杨迪,アンディ"
author:
  name: Di Yang
  email: hello@diyang.org
timezone: UTC
encoding: utf-8

url: https://www.diyang.org
repository: https://github.com/diyangorg/diyangorg.github.io
feed:
  en: /feed.xml
  zh: /订阅.xml
  ja: /フィード.xml
static_url: //cdn.diyang.org/static
media_url: //cdn.diyang.org/media

debug: false
analytics: UA-34085887-3

lsi: false
safe: true
highlighter: rouge
permalink: /:year/:month/:title/
relative_permalinks: false
markdown: kramdown

exclude:
- Gemfile
- Gemfile.lock
- Makefile
- Rakefile
- README.md
- LICENSE

defaults:
- scope:
    path: ""
    type: posts
  values:
    is_post: true

primary_color: "#86ae22"
