title:
  en: Di Yang
  zh: Di Yang
  ja: Di Yang
subtitle:
  en: "Hello, I'm Di Yang."
  zh: "Hello, I'm Di Yang."
  ja: "Hello, I'm Di Yang."
introduction:
  en: >
    <h1>Hello, I'm <a href="/about/">Di Yang</a>.</h1>
    <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h2>
  zh: >
    <h1>你好，我是<a href="/关于/">杨迪</a>。</h1>
    <h2>提就果學求鄉人像更又例團便的念這生高線工大更但海食告產每，確由去現旅；因事無民汽樣個列，解夫一去，本也美原、部且於上當爾好理的運我。</h2>
  ja: >
    <h1>こんにちは、私は<a href="/紹介/">アンディ</a>です。</h1>
    <h2>時間があるか分かりません。 私はいつも不思議な性格の方が好きだった。 すぐに諦めて昼寝をするかも知れない。 知らない。</h2>
keywords: "Di,Di Yang"
author:
  name: Di Yang
  email: hello@diyang.org
timezone: UTC
encoding: utf-8

url: https://www.diyang.org
repository: https://github.com/diyangorg/diyangorg.github.io
feed:
  en: /feed.xml
  zh: /订阅.xml
  ja: /フィード.xml
static_url: //cdn.diyang.org/static
media_url: //cdn.diyang.org/media

debug: false
analytics: UA-34085887-3

lsi: false
safe: true
highlighter: rouge
permalink: /:year/:month/:title/
relative_permalinks: false
markdown: kramdown

exclude:
- Gemfile
- Gemfile.lock
- Makefile
- Rakefile
- README.md
- LICENSE

defaults:
- scope:
    path: ""
    type: posts
  values:
    is_post: true

primary_color: "#86ae22"